# .travis.yml for 'stemr'

language: r
cache: packages
warnings_are_errors: true
sudo: required
install:
  - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages(c("Rcpp", "RcppArmadillo", "Ryacas", "odeintr", "optimx", "extraDistr", "ECctmc", "knitr", "testthat", "rmarkdown"), repos = "http://cran.rstudio.com")'
