#' Construct a list of functions for evaluating prior densities of model
#' parameters.
#'
#' @param priors list of parameters prior lists, each constructed via a call to
#'   the \code{\link{prior}} function.
#' @param param_codes vector of parameter codes as generated by the
#'   \code{\link{stem_dynamics}} function
#'
#' @return function to evaluate the prior densities, returning a vector
#' @export
construct_priors <- function(priors, param_codes) {

        if(length(priors) != length(param_codes)) {
                stop("All of the model parameters must have a prior distribution.")
        }

        # get the names of the parameters in the priors
        prior_params <- sapply(priors, "[[", "parameter")
        param_names  <- names(param_codes)

        # reorder the priors to match the parameters
        priors <- priors[match(param_names, prior_params)]

        # get the distributions, scales, hyperparameters, and parameters
        densities  <- paste0("d",sapply(priors, "[[", "distribution"))
        hyperpars  <- lapply(priors, "[[", "hyperpars"); hyperpar_args <- lapply(lapply(priors, "[[", "hyperpars"), names)
        hyperparameters <- mapply(paste, hyperpar_args, hyperpars, MoreArgs = list(collapse = ", ", sep = "="))

        # generate the body of the function
        prior_fcn_body <- paste0("sum(", paste0(densities, "(parameters[", seq_along(priors),"], ",  hyperparameters,", log = TRUE)", collapse = ", "), ")")

        prior_fcn <- eval(parse(text = paste0("function(parameters) {", prior_fcn_body, "}", sep = "\n")))

        return(prior_fcn)
}