#'Specify an MCMC transition kernel for updating the model parameters.
#'
#'@description Model parameters can be updated either using either componentwise
#'  or global Metropolis, with options for global or componentwise adaptive
#'  scaling.
#'
#'@param method algorithm to be used in generating parameter updates, see
#'  details below.
#'@param sigma vector of variances or variance-covariance matrix for random walk
#'  proposals, with names or rows and columns corresponding to the names of
#'  parameters on their estimation scales.
#'@param scale_constant constant multiple of the adaptations determined by
#'  \code{scale_cooling}.
#'@param scale_cooling rate at which to cool the adaptation, defaults to 0.5.
#'  Adaptation contributions are governed by a harmonic sequence:
#'  scale_constant/(iteration/step_size+1)^scale_cooling. The
#'  \code{plot_adaptations} function may be used to plot the adaptation factors.
#'@param step_size adaptation increment for each iteration, defaults to 1.
#'@param adaptation_offset iteration offset
#'@param max_scaling maximum scale factor, defaults to Inf.
#'@param target_g target acceptance rate for global Metropolis proposals.
#'@param nugget fixed nugget contribution, defaults 0.05 for afss, 0.01 for
#'  mvn_g_adaptive, and 0.5 for mvnss (cooling controlled in mvnss_settings)
#'@param stop_adaptation iteration at which to stop adapting the proposal
#'  distribution.
#'@param harss_warmup Number of hit-and-run warmup iterations, possibly
#'  interleaved with elliptical slice sampling warmup updates if ess_warmup =
#'  TRUE in the ess_settings list, performed prior to beginning the MCMC run.
#'  Defaults to 0.
#'@param afss_setting_list list of settings for automated factor slice sampling
#'  generated by the \code{afss_settings} function.
#'@param messages should messages be printed?
#'@param harss_setting_list list of settings for hit and run slice sampler
#'  generated by the \code{harss_settings} function.
#'@param mvnss_setting_list list of settings for multivariate normal slice
#'  sampler generated by the \code{mvnss_settings} function.
#'@param parameter_blocks list of parameter blocks each generated by a call to
#'  the parblock function. Parameters in each block are assumed to be
#'  independent and may either be updated jointly or sequentially
#'
#'@details Specifies the MCMC transition kernel for updating parameters, the
#'  latent epidemic process, time-varying parameters, and adaptive MCMC control.
#'  Parameter blocks group (time-homogeneous) parameters that are to be updated
#'  jointly. Each parameter block is updated via a multivariate
#'  Metropolis-Hastings update or a multivariate normal slice sampling update.
#'  Empirical covariances for these algorithms can be adapted using a global
#'  adaptive scaling algorithm (Andrieu and Thoms, 2008).
#'
#'  References 
#'  
#'  Andrieu, Christophe, and Johannes Thoms. "A tutorial on adaptive MCMC."
#'  Statistics and Computing 18.4 (2008): 343-373.
#'
#'@return list containing the MCMC kernel.
#'@export
mcmc_kernel <-
        function(parameter_blocks,
                 lna_ess_control = NULL,
                 initdist_ess_control = NULL,
                 tparam_ess_control = NULL,
                 adaptation_control = NULL) {

      kernel_settings = 
        list(parameter_blocks     = parameter_blocks,
             lna_ess_control      = lna_ess_control,
             initdist_ess_control = initdist_ess_control,
             tparam_ess_control   = tparam_ess_control,
             adaptation_control   = adaptation_control)
      
      return(kernel_settings)
}