#' Define a parameter block for an MCMC kernel
#'
#' @param pars either a numeric vector of parameter indices or a character
#'   vector of parameter names on their estimation scale (i.e., corresponding to
#'   row/column names in the kernel covariance matrix)
#' @param alg either "mvnmh"  or "mvnss" for multivariate normal metropolis
#'   hastings updates or multivariate normal slice sampling updates,
#'   respectively.
#' @param sigma initial covariance matrix for the parameter block, possibly to
#'   be adapted.
#' @param control list of mcmc control settings, generated by a call to
#'   \code{mvnmh_control} or \code{mvnss_control} as appropriate.
#'
#' @return parameter block for use in MCMC kernel
#' @export
parblock <- function(pars, alg, sigma, control = NULL) {
    
    if(!alg %in% c("mvnmh", "mvnss")) {
        stop("MCMC algorithm for updating parameters must be one of 'mvnmh' or 'mvnss'.")
    }
    
    if(is.null(control)) {
        control = 
            if(alg == "mvnmh") {
                mvnmh_control()
            } else {
                mvnss_control()
            }
    }
    
    if(is.null(control$nugget)) {
        control$nugget = 
            if(alg == "mvnmh") {
                control$nugget = 0.001 * min(diag(sigma))
            } else {
                control$nugget = 0.5
            }
    }
    
    return(list(pars = pars, alg = alg, sigma = sigma, control = control))
}