#' Simulations from a stochastic epidemic model.
#'
#' @param stem Stochastic epidemic model object, initialized with, at a minimum,
#' @param nsim number of realizations to simulate
#' @param paths Should population-level paths be returned?
#' @param observations Should simulated observations be returned? Requires that
#'   a measurement process be defined in the stem object.
#' @param subject_paths Should population-level paths be mapped to subject-level
#'   paths and returned (e.g. for the purpose of initializing a subject-level
#'   collection of disease histories)? Only available for exact simulation via
#'   the Gillespie direct method.
#' @param method either "gillespie" if simulating via Gillespie's direct method,
#'   or "LNA" if simulating paths via the Linear Noise Approximation.
#' @param times either a vector of observation times or a matrix of observation
#'   times. The name of the vector, or column names of the matrix, should
#'   indicate which compartment is being measured at the observation times. It
#'   not supplied, will be retrieved from the stem object.
#' @param timestep the timestep at which the population paths generated by an
#'   LNA solution should be evaluated.
#' @param time_discretization time discretization for smooth time-varying
#'   functions, specifically seasonal terms, to be used in simulation when
#'   method="gillespie". If not supplied, will default to the shortest period
#'   divided by 7 (e.g. if the period of a set of seasonal terms is 52, as for
#'   weekly periods, seasonality will be approximately constant for each day).
#'   Ignorable if method='LNA'.
#' @param as_array if TRUE, the simulated paths and/or simulated datasets will
#'   be returned as an array, or as a list containing multiple arrays (one for
#'   the paths, another for the datasets, and a third for subject-level paths if
#'   they are requested).
#'
#' @return If \code{paths = FALSE} and \code{observations = FALSE}, or if
#'   \code{paths = TRUE} and \code{observations = TRUE}, a list of \code{nsim
#'   stem} objects is returned, each with a dataset and the latent path from
#'   which it was simulated in the respective slots. If \code{subject_paths =
#'   TRUE} and \code{method = "gillespie"}, each \code{stem} object will also
#'   contain a matrix with a subject-level path.
#'
#'   If \code{paths = TRUE} and \code{observations = FALSE}, an array of
#'   simulated population-level paths is returned. If \code{method =
#'   "gillespie"} and \code{subject_paths = TRUE}, a list of two arrays is
#'   returned, with one array for population-level paths, and another for the
#'   subject-level mappings.
#'
#'   If \code{paths = FALSE} and \code{observations = TRUE}, an array of
#'   simulated datasets is returned.
#' @export
simulate_stem <- function(stem_object, nsim = 1, paths = FALSE, observations = FALSE, subject_paths = FALSE, method = "gillespie", times = NULL, timestep = NULL, time_discretization = NULL, as_array = FALSE) {

        if(!method %in% c("gillespie", "LNA")) {
                stop("The simulation method must either be 'gillespie' or 'LNA'.")
        }

        if(!subject_paths && (method == "LNA")) {
                warning("Subject-paths are only available when simulating paths when method='gillespie'.")
        }

        if(is.null(stem_object$dynamics)) {
                stop("The stochastic epidemic model dynamics must be specified.")
        }

        # compute the time discretization interval
        if(method == "gillespie" && is.null(timestep) && !is.null(stem_object$dynamics$tcovar_adjmat)) {
                tvarying <- which(sapply(names(stem_object$dynamics$param_codes), function(x) grepl("SIN", x)))
                s_param_names <- names(stem_object$dynamics$param_codes[tvarying])
                periods  <- as.numeric(unique(unlist(regmatches(s_param_names, gregexpr("[0-9]+", s_param_names)))))
                time_discretization <- 1/(7*max(periods))
        }


}