#' Generate a list of objects governing the measurement process for a stochastic
#' epidemic model.
#'
#' @param emissions list of emmision lists, each generated by a call to the
#'   \code{\link{emission}} function.
#' @param dynamics processed list of objects governing the model dynamics,
#'   returned by the \code{\link{stem_dynamics}} function.
#'
#' @return list with evaluated measurement process functions and objects.
#' @export
stem_measure <- function(emissions, dynamics) {

}